### ISSUE TITLE
Pandoc 1.14 and sre/rubber fork 

### ISSUE THREAD

**Issue by stola3** [synox/BFH-Latex_Bericht_Template_Markdown#2]
There is a problem with Pandoc 1.14 (27 May 15)

Lists are now based on `\tightlist` / tight list
- http://pandoc.org/releases.html (search for `tight list`/ `tightlist`)

However, rubber fork sre/rubber throws an error:

```
make rubber
...
rubber --pdf     --module bibtex --module index --module makeidx --module glossaries  main.tex
compiling main.tex...
kapitel/01_whatever.md.tex:169: Undefined control sequence \tightlist.
kapitel/01_whatever.md.tex:169: leading text: \tightlist
make: *** [rubber] Error 1
```

But pandoc 1.13.2.1 works fine => low prio!

**Comment by synox** [comment]
add this to your latex style document: 

```
    \providecommand{\tightlist}{%
      \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
```

source: https://github.com/jgm/pandoc-templates/blob/master/default.latex
